config/routes.rb
Rails.application.routes.draw do
  root "workorders#index"
  
  get 'signup' => 'users#new'
  resources :users
  
  resources :workorders

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  post 'logout', to: 'sessions#destory'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :workorders
end

app/models/workorder.rb
class Workorder < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    helper_method :current_user

    def current_user
        @current_user ||= User.find(session[:user_id]) if session[:user_id] 
    end

    def require_user
        redirect_to '/login' unless current_user 
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
    before_action :require_user_logged_in!
    def edit; end
    def update
      if Current.user.update(password_params)
        redirect_to root_path, notice: 'Password Updated'
      else
        render :edit
      end
    end
    
    private

    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        @user = User.find_by_username(params[:session][:username])
        if @user && @user.authenticate(params[:session][:password])
            session[:user_id] = @user.id
            redirect_to root_path
        else
            message = "Something went wrong! Make sure your username and password are correct."
            redirect_to login_path, notice: message
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to '/'
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :verify_authenticity_token 

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      redirect_to '/signup'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user, notice: 'Profile successfully updated.'
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :password)
  end
end

app/controllers/workorders_controller.rb
require 'pry'
class WorkordersController < ApplicationController
  before_action :require_user, only: [:show, :edit, :update, :destroy]
  before_action :set_workorder, only: [:show, :edit, :update, :destroy]


  def index
    @workorders = Workorder.all
  end
  
  def show
  end

  def new
    @workorder = Workorder.new
  end

  def create
    @workorder = Workorder.new(workorder_params)
    @workorder.user_id = current_user.id

    if @workorder.save
      redirect_to @workorder
    else
      render :new
    end
  end

  def edit
  end
  
  def update
    if @workorder.update(workorder_params)
      redirect_to @workorder, notice: 'Workorder successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @workorder = current_user.workorders.find(params[:id])
    @workorder.destroy

    redirect_to root_path, notice: 'Workorder has been successfully deleted.'
  end

  private
  def set_workorder
    @workorder = Workorder.find(params[:id])
  end

  def workorder_params
      params.require(:workorder).permit(:title, :description, :multiplier, :labor_hours, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def logged_in?
        !!session[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorkOrderApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  </head>

  <body>    
    <%= render "partials/main_nav" %>

    <main class="container-fluid mx-auto">
      <%= yield %>
    </main>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>

app/views/partials/_main_nav.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/"><%= image_tag("logo.png") %></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
    <% if current_user %>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Work Orders", workorders_path, class: "nav-link" %>
          </li>
        </ul>
          <div class="lg-ml-auto pl-0 user-menu dropdown">
            <a class="dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Manage Account
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Edit Profile", edit_user_path(current_user), class: "dropdown-item" %>
              <%= link_to "Log out", logout_path, method: "delete", class: "dropdown-item" %>
            </div>
          </div>
        <%# <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> %>
      </div>
    <% end %>
  </nav>
</header>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <div class="form-group">
        <%= f.text_field :username, placeholder:"Username", "aria-label": "Username", class: "form-control"  %>
    </div>
    <div class="form-group">
        <%= f.text_field :name, placeholder:"Name", "aria-label": "Name", class: "form-control" %>
    </div>
    <div class="form-group">
        <%= f.text_field :email,placeholder:"Email", "aria-label": "Email",  class: "form-control"  %>
    </div>
    <div class="form-group">
        <%= f.password_field :password, placeholder:"Password", "aria-label": "Password", class: "form-control"  %>
    </div>
    
    <%= f.submit action_name == "new" ? "Create Account" : "Save Changes", class: "btn btn-lg btn-primary btn-block mt-3" %>
<% end %>

app/views/users/edit.html.erb
<div class="w-25 mx-auto mt-3 text-center">
    <h1>Edit Profile</h1>
    <%= render "form", user: @user %>
</div>

app/views/users/new.html.erb
<div class="w-25 mx-auto mt-3 text-center">
    <h1>Creat an Account</h1>
    <%= render "form", workorder: @workorder %>
</div>

app/views/users/show.html.erb
<div class="w-25 mx-auto mt-3">
    <h1 class="text-center">Hi <%= @user.name %></h1>
    <div class="card">
        <div class="card-body">
            <div class="py-4 border-bottom">
                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <p class="card-text d-inline mr-5">Username</p>
                    </div>
                    <div class="col-sm-12 col-md-8">
                        <h5 class="sm-pl-0 md-pl-5 card-text d-inline"><%= @user.username %></h5>
                    </div>
                </div>
            </div>
            <div class="py-4 border-bottom">
                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <p class="card-text d-inline mr-5">Name</p>
                    </div>
                    <div class="col-sm-12 col-md-8">
                        <h5 class="sm-pl-0 md-pl-5 card-text d-inline"><%= @user.name %></h5>
                    </div>
                </div>
            </div>
            <div class="py-4 border-bottom">
                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <p class="card-text d-inline mr-5">Email</p>
                    </div>
                    <div class="col-sm-12 col-md-8">
                        <h5 class="sm-pl-0 md-pl-5 card-text d-inline"><%= @user.email %></h5>
                    </div>
                </div>
            </div>
            <div class="py-4">
                <div class="row">
                    <div class="col-sm-12 col-md-4">
                        <p class="card-text d-inline mr-5">Passwword</p>
                    </div>
                    <div class="col-sm-12 col-md-8">
                        <h5 class="sm-pl-0 md-pl-5 card-text d-inline"><%= link_to "Rest Password" %></h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%= link_to "Edit Profile", edit_user_path(current_user), class: "btn btn-lg btn-primary mt-3" %>
</div>

app/views/workorders/_form.html.erb
<%= form_for(@workorder) do |f| %>
  <div>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= f.label :title %><br>
    <%= f.text_field :title%>
    <% workorder.errors.full_messages_for(:title).each do |message| %>
      <div style="color:red;"><%= message %></div>
    <% end %>
  </div>
  <div>
    <%= f.label :multiplier %><br>
    <%= f.number_field :multiplier%>
  </div>
  <div>
    <%= f.label :labor_hours %><br>
    <%= f.number_field :labor_hours%>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description%>
  </div>
    <%= f.submit action_name == "new" ? "Create Workorder" : "Save Changes", class: "btn btn-lg btn-primary btn-block mt-3" %>
<% end %>

app/views/workorders/edit.html.erb
<h1>Edit Work Order <%= @workorder.title %></h1>
<%= render "form", workorder: @workorder %>

app/views/workorders/index.html.erb
<h1>Work Orders</h1>
<%= link_to "New Work Order", new_workorder_path, class: "purple"  %>

<div class="table-responsive">
  <table class="table">
    <thead>
      <th scope="col">Created Date</th>
      <th scope="col">Machine</th>
      <th scope="col">Multiplier</th>
      <th scope="col">Labor Hours</th>
      <th scope="col">Description</th>
      <th scope="col">Complete</th>
      <th scope="col">Settings</th>
    </thead>
    <tbody>
      <% @workorders.each do |w| %>
        <tr>
          <td><%= w.created_at.strftime("%B %d %Y") %></td>
          <td><%= link_to(@w) do %>
            <%= w.title %>
          <% end %></td>
          <td><%= w.multiplier %></td>
          <td><%= w.labor_hours %></td>
          <td><%= truncate(w.description, length: 30) %></td>
          <td>Complete</td>
          <td><%= link_to "Edit", edit_workorder_path(w) %></td>
          <td><%= button_to "Delete", w, method: :delete, data: {
                    confirm: "Are you sure?"
  }, class: 'text-danger'  %></td>
        <tr>
      <% end %>
    </tbody>
  </table>
</div>


app/views/workorders/new.html.erb
<h1>New Work Order</h1>
<%= render "form", workorder: @workorder %>

app/views/workorders/show.html.erb
<h1>Machine: <%= @workorder.title %></h1>
<p>Created: <%= @workorder.created_at %></p>
<p>Multiplier: <%= @workorder.multiplier %></p>
<p>Labor Hours: <%= @workorder.labor_hours %></p>
<p>Description: <%= @workorder.description %></p>
<ul>
  <li><%= link_to "Edit", edit_workorder_path(@workorder) %></li>
  <li><%= button_to "Delete", workorder_path, method: :delete, data: {
                    confirm: "Are you sure?"
  }, class: 'text-danger'  %></li>
</ul>